### ISSUE TITLE
Cpufriend i7-9750h

### ISSUE THREAD

**Issue by arypramudito** [athlonreg/Thunderobot-911-Air-i7-9750h#1]
Hi
Can you describe how to get kext for i7-9750H with cpufriend.kext via ssdtprgen ?
Maybe its better lowering to 500 for low freq same as i7-8750h

**Comment by athlonreg** [comment]
You can according to the readme guild of cpufriend. But as i known, 8750h and 9750h dont need it. Only you need is inject x86 according follow guild.
https://github.com/daliansky/OC-little/tree/master/03-%E6%B3%A8%E5%85%A5X86
