### ISSUE TITLE
我是雷神911me

### ISSUE THREAD

**Issue by Deeachain** [athlonreg/Thunderobot-911-Air-i7-9750h#2]
Hi，我的配置跟你一样，我用clover引导选安装系统，会出现禁行，主板需要设置什么嘛

**Comment by athlonreg** [comment]
> Hi，我的配置跟你一样，我用clover引导选安装系统，会出现禁行，主板需要设置什么嘛

换个usb口

**Comment by Deeachain** [comment]
> > Hi，我的配置跟你一样，我用clover引导选安装系统，会出现禁行，主板需要设置什么嘛
> 
> 换个usb口

我三个usb都试过了，还是不行，你的dmg镜像能共享一下嘛，我没能找到你的群怎么加，方便发一下嘛

**Comment by athlonreg** [comment]
> > > Hi，我的配置跟你一样，我用clover引导选安装系统，会出现禁行，主板需要设置什么嘛
> > 
> > 
> > 换个usb口
> 
> 我三个usb都试过了，还是不行，你的dmg镜像能共享一下嘛，我没能找到你的群怎么加，方便发一下嘛

项目README有群图片，镜像在我的专用共享站，加一下群里找吧

**Comment by Deeachain** [comment]
但是很遗憾的是，我没能发现你的readme中有群图片。私发我一个可还行？dingcheng0107@163.com

**Comment by athlonreg** [comment]
> 但是很遗憾的是，我没能发现你的readme中有群图片。私发我一个可还行？[dingcheng0107@163.com](mailto:dingcheng0107@163.com)

317496036
